### PR TITLE
Contracting

### PR DESCRIPTION
**Pull request by bubanoid**
This pull request contains all commits of the pull request https://github.com/openprocurement/openprocurement.client.python/pull/35 
It is extended with some unittests and is improved considerably.

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/openprocurement.client.python/47)

### CODE REVIEW

**Comment by selurvedu** [comment]
Все більш-менш ясно і виглядає досить гарно, але routing я не зрозумів.
Є ще два коментарі в #35, будь ласка, не забудь до них глянути.

---

Reviewed 19 of 20 files at r1.
Review status: 16 of 17 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[openprocurement_client/utils.py, line 3 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBPff9vZPFw09PShpI:-KjBPffAVh6vacOKMJDn:bg6wi7m) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/utils.py#L3)):*
> ```Python
> # -*- coding: utf-8 -*-
> from openprocurement_client.exceptions import IdNotFound
> from openprocurement_client.contract import ContractingClient
> ```

Ти забрав `client=ContractingClient('')` з `get_contract_id_by_uaid`, тому цей імпорт зайвий.

---

*[openprocurement_client/tests/_server.py, line 35 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBbGIdbbiINxFqd6jc:-KjBbGIdbbiINxFqd6jd:b-lra20f) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/_server.py#L35)):*
> ```Python
> def resource_filter(resource_name):
>     regexp = r'{}'.format(RESOURCE_DICT[resource_name]['sublink'])
>     return regexp, lambda x: resource_name, lambda x: None
> ```

Я не дуже зрозумів як працює цей фільтр і routing взагалі, поясни в двох словах, будь ласка.

---

*[openprocurement_client/tests/_server.py, line 147 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjB_qPwAnroTH61kU6A:-KjB_qPwAnroTH61kU6B:boet2wc) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/_server.py#L147)):*
> ```Python
> def patch_credentials(resource_name, resource_id):
>     resource = resource_partition(resource_id,
>                                                  resource_name)
> ```

Якийсь дивний тут відступ.

---

*[openprocurement_client/tests/_server.py, line 268 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBaLtkXtOu1PzQstKs:-KjBaLtl-NS9kxrf2hnJ:befnibx) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/_server.py#L268)):*
> ```Python
>     response.status = 200
>     change = resource_partition(change_id,
>                                           resource_name='change')
> ```

І тут відступ дивний.

---

*[openprocurement_client/tests/_server.py, line 309 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBitSYNka4LYqlttia:-KjBitSYNka4LYqlttib:b8du1fk) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/_server.py#L309)):*
> `# tender_subpage_item_patch`

?

---

*[openprocurement_client/tests/data_dict.py, line 19 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBQURyCGZrjzE_cZhB:-KjBQURzrFLLeP00J9MO:b4ylnsg) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/data_dict.py#L19)):*
> `"token": 'tender0token1234123412341234',  # uuid4().hex`

?

---

*[openprocurement_client/tests/tests.py, line 714 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBhNwkRw_D8Vj5EOEz:-KjBhNwkRw_D8Vj5EOF-:b-txqwh6) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/tests.py#L714)):*
> ```Python
>         self.assertEqual(response_change, patched_change)
> 
>     def test_get_contract_credentials(self):
> ```

Не забудь перейменувати тесткейс якщо перейменуєш функцію отримання токена.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-:-KjBSMSTh5NWdkAzbUbb:bobzuja)*

**Comment by bubanoid** [comment]
Review status: 16 of 17 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[openprocurement_client/utils.py, line 3 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBPff9vZPFw09PShpI:-KjCkNbCgdQeu_mbY8IT:b-896fix) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/utils.py#L3)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

Ти забрав `client=ContractingClient('')` з `get_contract_id_by_uaid`, тому цей імпорт зайвий.
</blockquote></details>

Done.

---

*[openprocurement_client/tests/_server.py, line 35 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBbGIdbbiINxFqd6jc:-KjDAPq87odXAPzZuOQb:b-pxotds) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/_server.py#L35)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

Я не дуже зрозумів як працює цей фільтр і routing взагалі, поясни в двох словах, будь ласка.
</blockquote></details>

При зустрічі вийшло би краще, але спробую тут.
В `_server.py` є лінійка:
`routes_dict = {'tenders':  ('/api/2.3/<resource_name:resource_filter:tender>', 'GET', resource_page_get),...}`
де вказано, що буде використано фільтр`resource_filter`. 'Аргументом' фільтра буде substring, а саме те, що у <...>. Substring `tender` у `<resource_name:resource_filter:tender>` означає, що у фільтр передається значення `tender`. Тобто `routes_dict['tenders']` зареєструє ф-цію `resource_page_get` на URL `.../api/2.3/tenders` (див. як означений сам фільтр і на константу `RESOURCE_DICT`). Cама ж функція `resource_page_get` приймає аргумент `resource_name`, який є результатом, який повертаєть після виклику другого елемента тьюпла, який повертає фільтр.

---

*[openprocurement_client/tests/_server.py, line 147 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjB_qPwAnroTH61kU6A:-KjCiwCxusdzXFqgRRLT:b-896fix) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/_server.py#L147)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

Якийсь дивний тут відступ.
</blockquote></details>

Done.

---

*[openprocurement_client/tests/_server.py, line 268 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBaLtkXtOu1PzQstKs:-KjCixmPKRz9kkQ7HzFB:b-896fix) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/_server.py#L268)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

І тут відступ дивний.
</blockquote></details>

Done.

---

*[openprocurement_client/tests/_server.py, line 309 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBitSYNka4LYqlttia:-KjCjJ4FKu_dxlxasAwI:b-9unw5o) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/_server.py#L309)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

> `# tender_subpage_item_patch`

?
</blockquote></details>

deleted

---

*[openprocurement_client/tests/data_dict.py, line 19 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBQURyCGZrjzE_cZhB:-KjCjPpa22_f_jTp6nua:b6tdi49) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/data_dict.py#L19)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

> `"token": 'tender0token1234123412341234',  # uuid4().hex`

?
</blockquote></details>

Що саме викликає питання? Коментар каже, що це `uuid4(),hex`.  Прибрати коментар?

---

*[openprocurement_client/tests/tests.py, line 714 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBhNwkRw_D8Vj5EOEz:-KjDUgMnXeuK5pJaheBs:bu5a2t2) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/tests.py#L714)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

Не забудь перейменувати тесткейс якщо перейменуєш функцію отримання токена.
</blockquote></details>

Я чогось не розумію. Тут нема функції отримання токена. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47)*

**Comment by selurvedu** [comment]
Reviewed 1 of 20 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 4 of 4 files at r4.
Review status: 12 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[openprocurement_client/tests/data_dict.py, line 19 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBQURyCGZrjzE_cZhB:-KjFDoNcvu7QN6AF4xUk:b-eggk3) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/data_dict.py#L19)):*
<details><summary><i>Previously, bubanoid (Andriy Andrusyk) wrote…</i></summary><blockquote>

Що саме викликає питання? Коментар каже, що це `uuid4(),hex`.  Прибрати коментар?
</blockquote></details>

Тоді символи в рядку мали б бути в діапазоні `0-9A-Fa-f`. :)

---

*[openprocurement_client/tests/tests.py, line 714 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBhNwkRw_D8Vj5EOEz:-KjFD7fZBbjetih3zSXm:bterqr4) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/tests.py#L714)):*
<details><summary><i>Previously, bubanoid (Andriy Andrusyk) wrote…</i></summary><blockquote>

Я чогось не розумію. Тут нема функції отримання токена. 
</blockquote></details>

Мало би бути `test_retrieve_contract_credentials`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47)*

**Comment by selurvedu** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openprocurement_client/tests/data_dict.py, line 19 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBQURyCGZrjzE_cZhB:-KjFMk9vDy-y2rchDbGk:b32w0x) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/data_dict.py#L19)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

Тоді символи в рядку мали б бути в діапазоні `0-9A-Fa-f`. :)
</blockquote></details>

OK

---

*[openprocurement_client/tests/tests.py, line 714 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-KjBhNwkRw_D8Vj5EOEz:-KjFPeRekM5HchXZeGT-:b32w0x) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/23e61229525bdbe34124f40f0747d53cbb2bccbe/openprocurement_client/tests/tests.py#L714)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

Мало би бути `test_retrieve_contract_credentials`.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/47#-:-KjFPiF_eUqE87I06O-Y:b-jbsf8z)*

**Pull request merged**
