### PR TITLE
Add retry for client.py where necessary

### PR DESCRIPTION
**Pull request by mykhaly**
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/openprocurement.client.python/27)

### CODE REVIEW

**Comment by selurvedu** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/27#-:-KEbx1RtzRYdsHDLZv7x:1417088721)*

**Comment by selurvedu** [comment]
:lgtm_cancel: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/27#-:-KEguKtXOcF0-3G-nwqD:502544406)*

**Comment by selurvedu** [comment]
А коли це востаннє апдейтилось?

**Comment by mykhaly** [comment]
18 березня)

**Comment by mykhaly** [comment]
Лол, code coverage збільшився)

**Pull request closed without merging**
