### PR TITLE
Add edr client

### PR DESCRIPTION
**Pull request by Krokop**
Потрібен для https://github.com/openprocurement/robot_tests/pull/494

---
This change is [Reviewable](https://reviewable.io/reviews/openprocurement/openprocurement.client.python/62)

### CODE REVIEW

**Comment by selurvedu** [comment]
Є лише одне зауваження, в решті все ОК.

---

Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[openprocurement_client/client.py, line 650 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/62#-Kh_jWGFexyz3FdUuuUb:-Kh_jWGFexyz3FdUuuUc:b2h1l47) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/03978cee564181b054af0f4401acde716c87e29f/openprocurement_client/client.py#L650)):*
> ```Python
>     """ Client for validate members by EDR """
> 
>     def __init__(self, host_url, username, password='', **kwargs):
> ```

Згідно з http://edr.api-docs.openprocurement.org/en/latest/authentication.html, доступ до API не буде працювати без пароля (на відміну від API тендерів). Варто зробити параметр password обов'язковим.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/62#-:-Kh_jwfVZBbNy9yGisFo:be715eg)*

**Comment by selurvedu** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/62)*

**Comment by Krokop** [comment]
*[openprocurement_client/client.py, line 650 at r1](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/62#-Kh_jWGFexyz3FdUuuUb:-Kha1u4Y2ouozE1mphCh:bb6un1j) ([raw file](https://github.com/openprocurement/openprocurement.client.python/blob/03978cee564181b054af0f4401acde716c87e29f/openprocurement_client/client.py#L650)):*
<details><summary><i>Previously, selurvedu wrote…</i></summary><blockquote>

Згідно з http://edr.api-docs.openprocurement.org/en/latest/authentication.html, доступ до API не буде працювати без пароля (на відміну від API тендерів). Варто зробити параметр password обов'язковим.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/62)*

**Comment by selurvedu** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openprocurement/openprocurement.client.python/62#-:-KhbymgtbE6NXhOzFTRt:bnfp4nl)*

**Pull request merged**
